Szakdolgozat/Controllers/AuthorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Szakdolgozat.BL.UnitOfWork;
using Szakdolgozat.DTO.Models;
using Szakdolgozat.DTO.ViewModels;

namespace Szakdolgozat.Web.Controllers
{
    [Authorize]
    public class AuthorController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public AuthorController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var authors = _unitOfWork.Authors.GetAll();
            var authorsVm = _mapper.Map<List<AuthorVm>>(authors);
            ViewData["Message"] = TempData["Message"];
            return View(authorsVm);
        }

        #region Add
        public IActionResult Create(int? id)
        {
            if (id == null)
                return View();

            var azon = int.Parse(id.ToString());
            var author = _unitOfWork.Authors.GetById(azon);
            if (author == null)
                return NotFound();

            var authorVm = _mapper.Map<AuthorVm>(author);
            return View(authorVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AuthorVm form)
        {
            if (ModelState.IsValid)
            {
                Author formCo = _mapper.Map<Author>(form);
                _unitOfWork.Authors.Add(formCo);
                _unitOfWork.Complate();
                TempData["Message"] = "Sikeres hozzáadás!";
                return RedirectToAction(nameof(Index));
            }
            return View(form);
        }
        #endregion

        #region Edit
        public IActionResult Edit(int id)
        {
            return RedirectToAction(nameof(Create), new { id = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(AuthorVm form)
        {
            if (ModelState.IsValid)
            {
                Author authorCo = _mapper.Map<Author>(form);
                try
                {
                    _unitOfWork.Authors.Update(authorCo);
                    _unitOfWork.Complate();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_unitOfWork.Authors.GetById(authorCo.Id) == null)
                        return NotFound();
                }
                TempData["Message"] = "A változtatásokat sikeresen elmentettük!";
                return RedirectToAction(nameof(Index));
            }
            return View(form);
        }
        #endregion

        #region Details
        public IActionResult Details(int id)
        {
            var authorCo = _unitOfWork.Authors.GetById(id);

            if (authorCo == null)
                return NotFound();

            var authorVm = _mapper.Map<AuthorVm>(authorCo);
            return View(authorVm);
        }
        #endregion

        #region Delete
        public IActionResult Delete(int id)
        {
            var authorCo = _unitOfWork.Authors.GetById(id);

            if (authorCo == null)
                return NotFound();

            var authorVm = _mapper.Map<AuthorVm>(authorCo);
            return View(authorVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var authorCo = _unitOfWork.Authors.GetById(id);
            _unitOfWork.Authors.Delete(authorCo);
            _unitOfWork.Complate();
            TempData["Message"] = "Sikeres törlés!";
            return RedirectToAction(nameof(Index));
        }
        #endregion
    }
}

Szakdolgozat/Controllers/BookAuthorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Szakdolgozat.BL.UnitOfWork;
using Szakdolgozat.DTO.Models;
using Szakdolgozat.DTO.ViewModels;

namespace Szakdolgozat.Web.Controllers
{
    public class BookAuthorController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public BookAuthorController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public IActionResult CreateWithAuthor(string authorId)
        {
            var authors = _unitOfWork.Authors.GetById(Convert.ToInt32(authorId));
            var authorVm = _mapper.Map<AuthorVm>(authors);
            ViewBag.author = authorVm.FirstName + " " + authorVm.LastName;

            IEnumerable<SelectListItem> bookItems = new List<SelectListItem>();

            var books = _unitOfWork.Books.GetAll();
            var bookVm = _mapper.Map<IEnumerable<BookVm>>(books);
            bookItems = bookVm.Select(b => new SelectListItem
                {
                    Text = b.Title,
                    Value = b.Id.ToString()
                });
            ViewBag.book = bookItems;
            return View();
        }

        [HttpPost]
        public IActionResult CreateWithAuthor(BookAuthorVm model)
        {
            if (ModelState.IsValid)
            {
                BookAuthor bookAuthor = _mapper.Map<BookAuthor>(model);
                _unitOfWork.BookAuthors.Add(bookAuthor);
                _unitOfWork.Complate();
                return RedirectToAction("Details", "Author", new { id = model.AuthorId });
            }
            return View(model);
        }

        public IActionResult CreateWithBook(string bookId)
        {
            IEnumerable<SelectListItem> authorItems = new List<SelectListItem>();
            var authors = _unitOfWork.Authors.GetAll();
            var authorVm = _mapper.Map<IEnumerable<AuthorVm>>(authors);
            authorItems = authorVm.Select(a => new SelectListItem
            {
                Text = a.LastName + " " + a.FirstName,
                Value = a.Id.ToString()
            });
            ViewBag.author = authorItems;

            var book = _unitOfWork.Books.GetById(Convert.ToInt32(bookId));
            var bookVm = _mapper.Map<BookVm>(book);
            ViewBag.book = bookVm.Title;

            return View();
        }

        [HttpPost]
        public IActionResult CreateWithBook(BookAuthorVm model)
        {
            if (ModelState.IsValid)
            {
                BookAuthor bookAuthor = _mapper.Map<BookAuthor>(model);
                _unitOfWork.BookAuthors.Add(bookAuthor);
                _unitOfWork.Complate();
                return RedirectToAction("Details", "Book", new { id = model.BookId });
            }
            return View(model);
        }

        public IActionResult Delete(int bookAuthorId)
        {
            ViewBag.Dest = ViewBag.Source;
            var bookAuthor = _unitOfWork.BookAuthors.GetById(bookAuthorId);

            if (bookAuthor == null)
                return NotFound();

            var authorVm = _mapper.Map<BookAuthorVm>(bookAuthor);
            return View(authorVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(BookAuthorVm model)
        {
            var bookAuthor = _unitOfWork.BookAuthors.GetById(model.Id);
            _unitOfWork.BookAuthors.Delete(bookAuthor);
            _unitOfWork.Complate();
            return RedirectToAction("Index", "Home");
        }        
    }
}

Szakdolgozat/Views/Author/Create.cshtml
@model Szakdolgozat.DTO.ViewModels.AuthorVm

<div class="row justify-content-center">
    <div class="col-8">
        @if (Model == null)
        {
            ViewData["Title"] = "Hozzáadás";
            <h1>Hozzáadás</h1>

            <h4>Szerző</h4>
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="LastName" class="control-label"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="FirstName" class="control-label"></label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Phone" class="control-label"></label>
                            <input asp-for="Phone" class="form-control" />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="EmailAddress" class="control-label"></label>
                            <input asp-for="EmailAddress" class="form-control" />
                            <span asp-validation-for="EmailAddress" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address" class="control-label"></label>
                            <input asp-for="Address" class="form-control" />
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="City" class="control-label"></label>
                            <input asp-for="City" class="form-control" />
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Zip" class="control-label"></label>
                            <input asp-for="Zip" class="form-control" />
                            <span asp-validation-for="Zip" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Mentés" class="btn btn-success" />
                        </div>
                    </form>
                </div>
            </div>

            <div>
                <a class="btn btn-info" asp-action="Index">Vissza</a>
            </div>
        }
        else
        {
            ViewData["Title"] = "Szerkesztés";
            <h1>Szerkesztés</h1>

            <h4>Szerző</h4>
            <hr />
            <div class="row">
                <div class="col-md-4">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group">
                            <label asp-for="LastName" class="control-label"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="FirstName" class="control-label"></label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Phone" class="control-label"></label>
                            <input asp-for="Phone" class="form-control" />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="EmailAddress" class="control-label"></label>
                            <input asp-for="EmailAddress" class="form-control" />
                            <span asp-validation-for="EmailAddress" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Address" class="control-label"></label>
                            <input asp-for="Address" class="form-control" />
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="City" class="control-label"></label>
                            <input asp-for="City" class="form-control" />
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Zip" class="control-label"></label>
                            <input asp-for="Zip" class="form-control" />
                            <span asp-validation-for="Zip" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Mentés" class="btn btn-success" />
                        </div>
                    </form>
                </div>
            </div>

            <div>
                <a class="btn btn-info" asp-action="Index">Vissza</a>
            </div>
        }
    </div>
</div>

Szakdolgozat/Views/Author/Delete.cshtml
@model Szakdolgozat.DTO.ViewModels.AuthorVm
@{
    ViewData["Title"] = "Törlés";
}

<h1>Törlés</h1>

<h3>Tényleg törölni szeretnéd?</h3>
<div>
    <h4>Szerző</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.LastName)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.LastName)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.FirstName)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.FirstName)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Phone)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Phone)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.EmailAddress)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.EmailAddress)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Address)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Address)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.City)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.City)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Zip)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => model.Zip)</dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Törlés" class="btn btn-danger" /> <br /><br />
        <a class="btn btn-info" asp-action="Index">Vissza</a>
    </form>
</div>

Szakdolgozat/Views/Author/Details.cshtml
@model Szakdolgozat.DTO.ViewModels.AuthorVm

@{
    ViewData["Title"] = "Részletek";
    ViewBag.Source = "Author";
}

<div class="container">
    <h1>Részletek</h1>

    <div>
        <h4>Szerző</h4>
        <hr />
        <div class="row">
            <dl class="col-6">
                <div class="row">
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.LastName)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.FirstName)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Phone)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Phone)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.EmailAddress)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.EmailAddress)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Address)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Address)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.City)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.City)
                    </dd>
                    <dt class="col-sm-4">
                        @Html.DisplayNameFor(model => model.Zip)
                    </dt>
                    <dd class="col-sm-8">
                        @Html.DisplayFor(model => model.Zip)
                    </dd>
                </div>                
            </dl>
            <dl class="col-6">
                <dt class="col-sm-2">
                    Könyvek:
                </dt>
                <dd class="col-sm-10">
                    <ul>
                        @foreach (var item in Model.BookAuthors)
                        {
                            <li>@Html.DisplayFor(modelItem => item.Book.Title) <a asp-action="Delete" asp-controller="BookAuthor" asp-route-bookAuthorId="@item.Id"><img alt="Minus_icon" src="~/Images/minus.svg" style="width: 20px;" /></a></li>
                        }
                    </ul>
                    <a asp-action="CreateWithAuthor" asp-controller="BookAuthor" asp-route-authorId="@Model.Id"><img alt="Plus_icon" src="~/Images/plus.svg"></a>
                </dd>
            </dl>
        </div>
    </div>
    <div>
        <a class="btn btn-secondary" asp-action="Edit" asp-route-id="@Model.Id">Szerkesztés</a>
        <a class="btn btn-info" asp-action="Index">Vissza</a>
    </div>
</div>

Szakdolgozat/Views/Author/Index.cshtml
@model IEnumerable<Szakdolgozat.DTO.ViewModels.AuthorVm>
@{
    ViewData["Title"] = "Szerző";
}

@if(ViewData["Message"] != null)
{
    <div class="alert alert-success alert-dismissible fade show text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Bezár">
            <span aria-hidden="true">&times;</span>
        </button>
        @ViewData["Message"]
    </div>
}

<h1>Szerzők</h1>

<p>
    @Html.ActionLink("Hozzáadás", "Create", new {}, new { @class = "btn btn-success" })
</p>

<table class="table">
    <tr>
        <th>@Html.DisplayNameFor(model => model.LastName)</th>
        <th>@Html.DisplayNameFor(model => model.FirstName)</th>
        <th>@Html.DisplayNameFor(model => model.Phone)</th>
        <th>@Html.DisplayNameFor(model => model.EmailAddress)</th>
        <th>@Html.DisplayNameFor(model => model.Address)</th>
        <th>@Html.DisplayNameFor(model => model.City)</th>
        <th>@Html.DisplayNameFor(model => model.Zip)</th>
        <th></th>
    </tr>
    @foreach(var item in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.LastName)</td>
            <td>@Html.DisplayFor(modelItem => item.FirstName)</td>
            <td>@Html.DisplayFor(modelItem => item.Phone)</td>
            <td>@Html.DisplayFor(modelItem => item.EmailAddress)</td>
            <td>@Html.DisplayFor(modelItem => item.Address)</td>
            <td>@Html.DisplayFor(modelItem => item.City)</td>
            <td>@Html.DisplayFor(modelItem => item.Zip)</td>
            <td>
                @Html.ActionLink("Részletek", "Details", new { id = item.Id }, new { @class = "btn btn-info" }) |
                @Html.ActionLink("Szerkesztés", "Edit", new { id = item.Id }, new { @class = "btn btn-secondary" }) |
                @Html.ActionLink("Törlés", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }
</table>