Szakdolgozat/Controllers/AuthorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using Szakdolgozat.BL.UnitOfWork;
using Szakdolgozat.DTO.Models;
using Szakdolgozat.DTO.ViewModels;

namespace Szakdolgozat.Web.Controllers
{
    [Authorize]
    public class AuthorController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public AuthorController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var authors = _unitOfWork.Authors.GetAll();
            var authorsVm = _mapper.Map<List<AuthorVm>>(authors);
            ViewData["Message"] = TempData["Message"];
            return View(authorsVm);
        }

        #region Add
        public IActionResult Create(int? id)
        {
            if (id == null)
                return View();

            var azon = int.Parse(id.ToString());
            var author = _unitOfWork.Authors.GetById(azon);
            if (author == null)
                return NotFound();

            var authorVm = _mapper.Map<AuthorVm>(author);
            return View(authorVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AuthorVm form)
        {
            if (ModelState.IsValid)
            {
                Author formCo = _mapper.Map<Author>(form);
                _unitOfWork.Authors.Add(formCo);
                _unitOfWork.Complate();
                TempData["Message"] = "Sikeres hozzáadás!";
                return RedirectToAction(nameof(Index));
            }
            return View(form);
        }
        #endregion

        #region Edit
        public IActionResult Edit(int id)
        {
            return RedirectToAction(nameof(Create), new { id = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(AuthorVm form)
        {
            if (ModelState.IsValid)
            {
                Author authorCo = _mapper.Map<Author>(form);
                try
                {
                    _unitOfWork.Authors.Update(authorCo);
                    _unitOfWork.Complate();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (_unitOfWork.Authors.GetById(authorCo.Id) == null)
                        return NotFound();
                }
                TempData["Message"] = "A változtatásokat sikeresen elmentettük!";
                return RedirectToAction(nameof(Index));
            }
            return View(form);
        }
        #endregion

        #region Details
        public IActionResult Details(int id)
        {
            var authorCo = _unitOfWork.Authors.GetById(id);

            if (authorCo == null)
                return NotFound();

            var authorVm = _mapper.Map<AuthorVm>(authorCo);
            return View(authorVm);
        }
        #endregion

        #region Delete
        public IActionResult Delete(int id)
        {
            var authorCo = _unitOfWork.Authors.GetById(id);

            if (authorCo == null)
                return NotFound();

            var authorVm = _mapper.Map<AuthorVm>(authorCo);
            return View(authorVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var authorCo = _unitOfWork.Authors.GetById(id);
            _unitOfWork.Authors.Delete(authorCo);
            _unitOfWork.Complate();
            TempData["Message"] = "Sikeres törlés!";
            return RedirectToAction(nameof(Index));
        }
        #endregion
    }
}

Szakdolgozat/Controllers/JobController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Szakdolgozat.BL.UnitOfWork;
using Szakdolgozat.DTO.Models;
using Szakdolgozat.DTO.ViewModels;

namespace Szakdolgozat.Web.Controllers
{
    [Authorize]
    public class JobController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public JobController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var jobs = _unitOfWork.Jobs.GetAll();
            var jobVm = _mapper.Map<List<JobVm>>(jobs);
            ViewData["Message"] = TempData["Message"];
            return View(jobVm);
        }

        #region Add
        public IActionResult Create(int? id)
        {
            if (id == null)
                return View();

            var azon = int.Parse(id.ToString());
            var job = _unitOfWork.Jobs.GetById(azon);
            if (job == null)
                return NotFound();

            var jobVm = _mapper.Map<JobVm>(job);
            return View(jobVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(JobVm form)
        {
            if (ModelState.IsValid)
            {
                Job formCo = _mapper.Map<Job>(form);
                _unitOfWork.Jobs.Add(formCo);
                _unitOfWork.Complate();
                TempData["Message"] = "Sikeres hozzáadás!";
                return RedirectToAction(nameof(Index));
            }
            return View(form);
        }
        #endregion

        #region Edit
        public IActionResult Edit(int id)
        {
            return RedirectToAction(nameof(Create), new { id = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(JobVm form)
        {
            if (ModelState.IsValid)
            {
                Job jobCo = _mapper.Map<Job>(form);
                _unitOfWork.Jobs.Update(jobCo);
                _unitOfWork.Complate();

                TempData["Message"] = "A változtatásokat sikeresen elmentettük!";
                return RedirectToAction(nameof(Index));
            }
            return View(form);
        }
        #endregion

        #region Details
        public IActionResult Details(int id)
        {
            var jobCo = _unitOfWork.Jobs.GetById(id);

            if (jobCo == null)
                return NotFound();

            var jobVm = _mapper.Map<JobVm>(jobCo);
            return View(jobVm);
        }
        #endregion

        #region Delete
        public IActionResult Delete(int id)
        {
            var jobCo = _unitOfWork.Jobs.GetById(id);

            if (jobCo == null)
                return NotFound();

            var jobVm = _mapper.Map<JobVm>(jobCo);
            return View(jobVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var jobCo = _unitOfWork.Jobs.GetById(id);
            _unitOfWork.Jobs.Delete(jobCo);
            _unitOfWork.Complate();
            TempData["Message"] = "Sikeres törlés!";
            return RedirectToAction(nameof(Index));
        }
        #endregion
    }
}

Szakdolgozat/Controllers/SaleController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using Szakdolgozat.BL.UnitOfWork;
using Szakdolgozat.DTO.Models;
using Szakdolgozat.DTO.ViewModels;

namespace Szakdolgozat.Web.Controllers
{
    [Authorize]
    public class SaleController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public SaleController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var sales = _unitOfWork.Sales.GetAll();
            var saleVm = _mapper.Map<List<SaleVm>>(sales);
            ViewData["Message"] = TempData["Message"];
            return View(saleVm);
        }

        #region Add
        public IActionResult Create(int? id)
        {
            IEnumerable<SelectListItem> storeItems = new List<SelectListItem>();
            IEnumerable<SelectListItem> bookItems = new List<SelectListItem>();
            var stores = _unitOfWork.Stores.GetAll();
            var storeVm = _mapper.Map<IEnumerable<StoreVm>>(stores);
            storeItems = storeVm.Select(p => new SelectListItem
            {
                Text = p.StoreName,
                Value = p.Id.ToString()
            });
            var books = _unitOfWork.Books.GetAll();
            var bookVm = _mapper.Map<IEnumerable<BookVm>>(books);
            bookItems = bookVm.Select(p => new SelectListItem
            {
                Text = p.Title,
                Value = p.Id.ToString()
            });

            ViewBag.Store = storeItems;
            ViewBag.Book = bookItems;

            if (id == null)
                return View();

            var azon = int.Parse(id.ToString());
            var sale = _unitOfWork.Sales.GetById(azon);
            if (sale == null)
                return NotFound();

            var saleVm = _mapper.Map<SaleVm>(sale);
            return View(saleVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SaleVm form)
        {
            if (ModelState.IsValid)
            {
                Sale formCo = _mapper.Map<Sale>(form);
                _unitOfWork.Sales.Add(formCo);
                _unitOfWork.Complate();
                TempData["Message"] = "Sikeres hozzáadás!";
                return RedirectToAction(nameof(Index));
            }
            return View(form);
        }
        #endregion

        #region Edit
        public IActionResult Edit(int id)
        {
            return RedirectToAction(nameof(Create), new { id = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SaleVm form)
        {
            if (ModelState.IsValid)
            {
                Sale saleCo = _mapper.Map<Sale>(form);
                _unitOfWork.Sales.Update(saleCo);
                _unitOfWork.Complate();

                TempData["Message"] = "A változtatásokat sikeresen elmentettük!";
                return RedirectToAction(nameof(Index));
            }
            return View(form);
        }
        #endregion

        #region Details
        public IActionResult Details(int id)
        {
            var saleCo = _unitOfWork.Sales.GetById(id);

            if (saleCo == null)
                return NotFound();

            var saleVm = _mapper.Map<SaleVm>(saleCo);
            return View(saleVm);
        }
        #endregion

        #region Delete
        public IActionResult Delete(int id)
        {
            var saleCo = _unitOfWork.Sales.GetById(id);

            if (saleCo == null)
                return NotFound();

            var saleVm = _mapper.Map<SaleVm>(saleCo);
            return View(saleVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var saleCo = _unitOfWork.Sales.GetById(id);
            _unitOfWork.Sales.Delete(saleCo);
            _unitOfWork.Complate();
            TempData["Message"] = "Sikeres törlés!";
            return RedirectToAction(nameof(Index));
        }
        #endregion
    }
}

Szakdolgozat/Controllers/StoreController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using Szakdolgozat.BL.UnitOfWork;
using Szakdolgozat.DTO.Models;
using Szakdolgozat.DTO.ViewModels;

namespace Szakdolgozat.Web.Controllers
{
    [Authorize]
    public class StoreController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public StoreController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var stores = _unitOfWork.Stores.GetAll();
            var storeVm = _mapper.Map<List<StoreVm>>(stores);
            ViewData["Message"] = TempData["Message"];
            return View(storeVm);
        }

        #region Add
        public IActionResult Create(int? id)
        {
            if (id == null)
                return View();

            var azon = int.Parse(id.ToString());
            var store = _unitOfWork.Stores.GetById(azon);
            if (store == null)
                return NotFound();

            var storeVm = _mapper.Map<StoreVm>(store);
            return View(storeVm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(StoreVm form)
        {
            if (ModelState.IsValid)
            {
                Store formCo = _mapper.Map<Store>(form);
                _unitOfWork.Stores.Add(formCo);
                _unitOfWork.Complate();
                TempData["Message"] = "Sikeres hozzáadás!";
                return RedirectToAction(nameof(Index));
            }
            return View(form);
        }
        #endregion

        #region Edit
        public IActionResult Edit(int id)
        {
            return RedirectToAction(nameof(Create), new { id = id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(StoreVm form)
        {
            if (ModelState.IsValid)
            {
                Store storeCo = _mapper.Map<Store>(form);
                _unitOfWork.Stores.Update(storeCo);
                _unitOfWork.Complate();

                TempData["Message"] = "A változtatásokat sikeresen elmentettük!";
                return RedirectToAction(nameof(Index));
            }
            return View(form);
        }
        #endregion

        #region Details
        public IActionResult Details(int id)
        {
            var storeCo = _unitOfWork.Stores.GetById(id);

            if (storeCo == null)
                return NotFound();

            var storeVm = _mapper.Map<StoreVm>(storeCo);
            return View(storeVm);
        }
        #endregion

        #region Delete
        public IActionResult Delete(int id)
        {
            var storeCo = _unitOfWork.Stores.GetById(id);

            if (storeCo == null)
                return NotFound();

            var storeVm = _mapper.Map<StoreVm>(storeCo);
            return View(storeVm);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            var storeCo = _unitOfWork.Stores.GetById(id);
            _unitOfWork.Stores.Delete(storeCo);
            _unitOfWork.Complate();
            TempData["Message"] = "Sikeres törlés!";
            return RedirectToAction(nameof(Index));
        }
        #endregion
    }
}

Szakdolgozat/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h1>@ViewBag.ErrorMessage</h1>

<a asp-action="Index" asp-controller="Home">Vissza a kezdő oldalra</a>

Szakdolgozat/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Szakdolgozat</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @if (signInManager.IsSignedIn(User))
                {
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Szakdolgozat</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse">
                    <ul class="navbar-nav">
                        @if(User.IsInRole("Admin")) 
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="ListRoles">Admin</a>
                            </li>
                        }                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Szerzők</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publisher" asp-action="Index">Kiadók</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Könyvek</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Job" asp-action="Index">Beosztások</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="Index">Üzletek</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sale" asp-action="Index">Eladások</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        Hello @User.Identity.Name
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">Kijelentkezés</a>
                        </li>
                    </ul>
                </div>
                }
                else
                {
                <a class="navbar-brand">Szakdolgozat</a>
                }

            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Szakdolgozat - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>